### ISSUE TITLE
Feedback for X-Air Channels

### ISSUE THREAD

**Issue by chriskooken** [bitfocus/companion-module-behringer-xair#1]
**Describe the feature**
Would like to have feedback availible so I can change the button color when a channel, bus or main is muted or hot.

**Is this platform dependent (windows, mac, ..)?**
No.

**Usecases**
Right now, if you mute via X-Air app, it doest reflect on the StreamDeck. Would be very nice to have a view of the status on the StreamDeck.

**Comment by smadds** [comment]
+1 for that please!

**Comment by krocheck** [comment]
@istnv since you're on a roll ... you wanna take this one too and close out all the xair issues? :)

**Comment by istnv** [comment]
I'm actually working out a way to do that.
I have a generated list of channel strips (OSC addresses) to watch, and that works.
I can track updates from the mixer as well.
I need to poll for the existing status at module start and I'm running into a throughput problem. 
UDP sockets don't guarantee delivery so if I ask for all 40 channels at once, the mixer doesn't keep up and several are missed.

**Comment by krocheck** [comment]
This is now in the 2.0 beta builds
