### ISSUE TITLE
x-air audio crashes when not attached to audio system

### ISSUE THREAD

**Issue by ChrisSW58** [bitfocus/companion-module-behringer-xair#108]
x-air module version on 3.5.0 beta crashes when not physically connected to hardware. Goes into unending retry loop. Means you cannot code against x-air variables unless physically connected to the x-air (behringer) kit. In 3.4.x, when not connected, it stated "Connection Failure" yet module was still available to code against. Running on latest MacOS. Log states:
24.10.01 03:01:59 Instance/ModuleHost: Connection "Xair_Audio" started
24.10.01 03:01:59 Instance/ModuleHost: Registered module client "6wFQmQGuGZ8IE5ReqddNe"
24.10.01 03:01:59 Instance/ModuleHost: Unhandled error restarting connection: Error: Restart forced
24.10.01 03:01:59 Instance/ModuleHost: Connection "Xair_Audio" stopped

**Comment by istnv** [comment]
Nothing has changed since the last 3.4.1 stable release.
There are some issues with the current betas.

**Comment by ChrisSW58** [comment]
Thanks for the response. Just for completeness here's the equivalent log from 3.4.1, which doesn't have the unhandled error noted in the previous log. I will await an updated beta. :)

                  log: You can view older logs in the configuration folder

24.10.01 13:30:38 Instance/ModuleHost: Connection "Xair_Audio" started
24.10.01 13:30:38 Instance/ModuleHost: Registered module client "6wFQmQGuGZ8IE5ReqddNe"
24.10.01 13:30:38 Instance/Controller: instance "Xair_Audio" configuration updated
24.10.01 13:30:57 Instance/Wrapper/Xair_Audio: 10.0.3.2 not responding

**Comment by modF** [comment]
I am checking in with the same issue, but adding "Connection config unavailable" to the endlees loop.

**Comment by istnv** [comment]
@modF Which OS?

**Comment by ChrisSW58** [comment]
> [@modF](https://github.com/modF) Which OS?

For me it is Mac OS

**Comment by ChrisSW58** [comment]
This is still happening on 3.5.0 7514

**Comment by istnv** [comment]
Are you importing an old config file?

**Comment by istnv** [comment]
@ChrisSW58 
I moved this to a new issue since it is not the same issue.
"The car won't start" could be battery, gas, no key, or several other things.

**Comment by ChrisSW58** [comment]
Totally get that - many thanks. Using the car analogy I was simply addressing the “Your car’s fixed now” statement. 😆

**Comment by ChrisSW58** [comment]
> Are you importing an old config file?

And yes it was a 3.4.2 config file
