### ISSUE TITLE
Error importing old configs

### ISSUE THREAD

**Issue by istnv** [bitfocus/companion-module-behringer-xair#112]
> @istnv This is still happening on 3.5.0 7514
> 
> system: ** Starting Connection from "/Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js" **
> system: ** Connection started **
> Starting up module class: b
> Module-host accepted registration
> error: Failed to init: Error: Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
>     at n.snap_color (/Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:559644)
>     at t.runThroughUpgradeScripts (/Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:229820)
>     at /Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:234677
>     at /Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:122483
>     at t.default._tryToStartAnother (/Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:121530)
>     at /Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:122690
>     at new Promise (<anonymous>)
>     at t.default.add (/Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:122333)
>     at b._handleInit (/Applications/Companion.app/Contents/Resources/bundled-modules/behringer-xair/main.js:1:234281)
> system: ** Connection stopped ** 

 _Originally posted by @ChrisSW58 in [#108](https://github.com/bitfocus/companion-module-behringer-xair/issues/108#issuecomment-2442725753)_

**Comment by ChrisSW58** [comment]
Many thanks - good work!
