### ISSUE TITLE
Mute Group Indicator not working for XR18

### ISSUE THREAD

**Issue by ScottKemp** [bitfocus/companion-module-behringer-xair#117]
I was able to get a button to control a mute group, but not inidcate its status.

Had no problem with a SOLO Button (Pushed and indcated) so I know things are working bidirectionally. 

![Image](https://github.com/user-attachments/assets/259140e0-f05f-4024-95d2-d7f7e9ecad1a)

Looks like the Mute status is received.  But the button does not change to a red background.

![Image](https://github.com/user-attachments/assets/f2322cd1-e5b3-48b8-813a-6b15e9394b7b)

**Comment by ScottKemp** [comment]
@intnv Thank you for fixing this so quickly.  I was unable to figure out how to update my Companion installation to incorporate this fix.  Tips?

**Comment by istnv** [comment]
@ScottKemp It is in the recent beta releases.

**Comment by ScottKemp** [comment]
Is it easy to install the Beta?  How?

**Comment by istnv** [comment]
Download from the bitfocus.io website. Same place as the stable releases.

**Comment by ScottKemp** [comment]
I see.  I thought maybe each module had their own "releases" or updates.  Thanks again for fixing that so quickly



------ Original Message ------
From "John Knight Jr" ***@***.******@***.***>>
To "bitfocus/companion-module-behringer-xair" ***@***.******@***.***>>
Cc "Scott M. Kemp" ***@***.******@***.***>>; "Mention" ***@***.******@***.***>>
Date 11/12/2024 7:45:37 PM
Subject Re: [bitfocus/companion-module-behringer-xair] Mute Group Indicator not working for XR18 (Issue #117)


Download from the bitfocus.io website. Same place as the stable releases.
