### ISSUE TITLE
[Request] Add mute state variable of channels and busses

### ISSUE THREAD

**Issue by Wiethoofd** [bitfocus/companion-module-behringer-xair#119]
It could be useful to have the '(un)muted' state of a channel or bus as a variable to display as text on a button, not just the visual feedback.

The OBS companion module has this for audio sources; the feedback state having the textual representation has come in handy more than once.

![Image](https://github.com/user-attachments/assets/d2554ee0-00d2-42ca-a8c2-304f6f34ae89)

**Comment by istnv** [comment]
You can also add 'text' to the button via the `muted` feedback.

**Comment by istnv** [comment]
You can also set a variable via trigger.
