### ISSUE TITLE
Mixer Not Detected Due to Broadcast Method

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#126]
I've had multiple clients report that their mixer isn't detected by Companion. After investigating, the issue seems to stem from the `255.255.255.255` xinfo broadcast.

### Findings:
- In my custom scripts, I resolved the issue by sending the broadcast specifically to the default gateway + `.255` instead of using `255.255.255.255`. Modifying the Companion module to do the same also worked.
- Interestingly, the Behringer XR/MR Edit apps don't seem to face this issue. My guess is that these apps detect all IP addresses on the machine (which would explain the weird "IP Address(es)" debug text in the setup window) and send the xinfo broadcast to each address with the last octet set to `.255`.

### Suggestion:
It might be worth adapting the module to dynamically detect the machine's IP addresses and use the subnet-specific broadcast address (e.g., `192.168.1.255`). This approach seems more reliable, especially on machines with unusual network adapter configurations or routers that block wide-scale broadcasts.

I haven't tested this theory yet, but based on how the Behringer apps behave (if I understand it well), it should work.

**Comment by istnv** [comment]
No guarantees there. I have a setup where XEdit consistently fails probing for a mixer, yet manual IP finds it every time.

**Comment by Mozoloa** [comment]
I believe I've had this years ago but not since then. XR edit has always found the mixer when my scripts and companion fail often. Isn't my suggestion the most sensible approach ? There can't be a situation where the mixer is not near the host pc in the address range technically, else it wouldn't be visible at all. Idk

**Comment by istnv** [comment]
I have one where the laptop is less than a meter from the console, on the same switch, and still does not find it without manual IP.
Recent network rules are filtering the broadcast address unless you allow through the firewall. I'll try this out when I have some time.

**Comment by istnv** [comment]
@Mozoloa 
Looks good. Update the version # in `package.json` in your PR and I'll merge when I can.

**Comment by Mozoloa** [comment]
All good
