### ISSUE TITLE
Behringer X-AIR DCA fader adjust & fader set (Companion 2.1.1 (acb83e9-2660))

### ISSUE THREAD

**Issue by leovangaal** [bitfocus/companion-module-behringer-xair#22]
Companion crashes when using the fader adjust commands for the DCA masters in this beta version.
The fader set function is not working for the DCA masters.

I tried the channels, SUBS and LR master. They are working fine.
But with hno programming background I've got no clue where to look for in all the coding ;-)

Thanks for your time and effort to check this error. This beta is a huge update for the X-Air series!

**Comment by istnv** [comment]
I'll check this today.

**Comment by leovangaal** [comment]
Thanks for your quick reply and solution!

**Comment by enochchan** [comment]
May I ask what is the best way to update the module?

I am asking because I was trying to set use companion to set DCA fader level yesterday, but there was no response from the mixer; and I suspect that the above mentioned fix could be applied to fix the same issue that I was having too.  

Thanks!

**Comment by istnv** [comment]
@enochchan  There is no individual module update. The fix/patch is applied to the module then Companion is completely rebuilt. You need to download the latest version of Companion.

**Comment by enochchan** [comment]
> @enochchan  There is no individual module update. The fix/patch is applied to the module then Companion is completely rebuilt. You need to download the latest version of Companion.

Thank you for the reply and will try soon!
