### ISSUE TITLE
optional duration parameter for fades is missing 

### ISSUE THREAD

**Issue by tsm-dev-hub** [bitfocus/companion-module-behringer-xair#30]
Hi. I see in the notes "Fader changes also have an optional duration of 0 to 60000 mSec (0 to 60 seconds) to create cross fades." However, there is no duration parameter in the options area for Fader Adjust or Fader Set. Am I missing something?
<img width="622" alt="Screen Shot 2021-04-06 at 11 01 07 pm" src="https://user-images.githubusercontent.com/70609927/113714704-04cf9400-972c-11eb-8561-d1d1e2510f09.png">

**Comment by tsm-dev-hub** [comment]
Aha I see.. that's great! Sorry if this is a noob question but how do I install the latest beta version?

BTW Thanks very much for writing the module.

**Comment by istnv** [comment]
![image](https://user-images.githubusercontent.com/51003420/113792803-a5599000-96fb-11eb-8bdf-82038a89f655.png)

**Comment by tsm-dev-hub** [comment]
aha.. Companion beta. Got it. And tried it. Works a treat. Thank you.
