### ISSUE TITLE
Can't set duration of fader set

### ISSUE THREAD

**Issue by adieball** [bitfocus/companion-module-behringer-xair#31]
Hi

in fader set or fader adjust, how do I set the duration as explained in the readme? there is no filed for this.

thanks

**Comment by McHauge** [comment]
@adieball What version of companion are you using? 2.1.2, 2.1.3 or beta 2.2.0? it just makes it simpler to track, if you know what people are using :)

**Comment by istnv** [comment]
2.1.3 includes the most recent version.
![image](https://user-images.githubusercontent.com/51003420/116270258-caa65080-a733-11eb-8b1c-1aaaa798dc0a.png)

**Comment by adieball** [comment]
running 2.1.2, will update now and keep you posted, thanks a lot

**Comment by adieball** [comment]
2.1.3 works fine. thanks
