### ISSUE TITLE
Load Snapshots

### ISSUE THREAD

**Issue by ManuelStream** [bitfocus/companion-module-behringer-xair#33]
Hey,

is it possible to read the names of the snapshot list so that I can display variable text on the stream deck? At the moment I can only read the name of the current Snap.

greetings

**Comment by istnv** [comment]
I am adding Snapshot navigation as well as the names. (Load previous, load next) 
Those commands are not in the standard protocol, but once the snapshot list is loaded, it is not that difficult to do.

**Comment by ManuelStream** [comment]
okay, thank you very much for your effort

**Comment by ManuelStream** [comment]
Sorry, I have to ask stupid questions. How do I get the changes or additions updated?

**Comment by istnv** [comment]
It is waiting on core developer approval then it will be included. It should be available this week.

**Comment by ManuelStream** [comment]
Okay, thank you very much for the information and the programming work.

**Comment by ManuelStream** [comment]
Hey istnv,

the Update is now available, but I fail with the implementation. What do I have to do to install the new Version?

**Comment by istnv** [comment]
This update is only in the 2.2.0 version (beta). Click where it says 'Beta builds':
![image](https://user-images.githubusercontent.com/51003420/124502692-ca9c7f80-dd78-11eb-9301-6c8b73f42362.png)
