### ISSUE TITLE
Fader Set for Bus Channels

### ISSUE THREAD

**Issue by kleinandr** [bitfocus/companion-module-behringer-xair#37]
Hi,
I need to change the Fader Set of Channel 1-16 not only in the MAIN Bus L+R, but in Bus 1 und Bus 2 as well, because they are connected to separate speakers in our church. Is this possible? In the moment I only can set the Level for MAIN, not in the BUS.

Best regards
Andreas

**Comment by istnv** [comment]
The action for bus sends are called 'Send level':
![image](https://user-images.githubusercontent.com/51003420/123139236-dac46e80-d40a-11eb-9708-e947540bf810.png)

**Comment by kleinandr** [comment]
Great help! Thank you - I never would have found this!
