### ISSUE TITLE
"Error: Cannot set property 'name' of undefined"

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#45]
Hello, 

I very often have this error where the buttons get a little red square in the corner and no message is being transmitted.

This seems to happen randomly (or sometimes when the pc gets out of sleep) and only the following error pops in the logs:
"Error: Cannot set property 'name' of undefined"

This has been happening on dozens of computers I've set up with this instance and usually just clicking edit and save on the instance seems to fix it.

**Comment by istnv** [comment]
There have been several updates since this.
Re-open if it is still a problem.

**Comment by Mozoloa** [comment]
For now I just have a trigger to restart the instance if there's an error with an instance, so I'm not sure it's doing it anymore

**Comment by Mozoloa** [comment]
23.03.03 20:06:18 instance(xair): Error: Cannot set property 'name' of undefined

It actually just did on 2.4.1

**Comment by Mozoloa** [comment]
All the buttons show a little red square on the upper right, and most actions don't go through, and feedbacks seem broken as well, it's not just certain buttons, this error affects everything. Disabling/Enabling fixes it like in 2021, I though about removing the trigger that restarts the instance whenever there's an error, but I'll have to keep it for now

**Comment by istnv** [comment]
The red square indicates a module error. Typically a lost connection to the mixer, but that error will crash the module and disable it.
The log should also show which button was pressed when the error happened.
What actions are on that button?

**Comment by Mozoloa** [comment]
I don't have the log anymore, but I copied the only line I saw

**Comment by istnv** [comment]
Do you use a lot of snapshots with the XAir mixers?

Companion 3.0 will have a nearly complete re-write for this module soon. I am testing it now.

**Comment by Mozoloa** [comment]
Yes a lot of the changes use snapshots, I don't think I've had the problem in a very long time myself, usually it did it when resuming from sleep, but this week I had it at one of my client's place seemingly randomly so I was surprised. Pretty hyped to test the 3.0 module, I'm hoping to see some more functionalities like routing and the likes

**Comment by istnv** [comment]
No new stuff in the initial 3.0 version. Just a rewrite to comply with the newer companion structure.
Please write up a feature request for what you want for the routing. 
The features in the module were ones most commonly needed/used live, whereas routing is a configuration function much easier done with the edit/setup software or a snapshot if necessary.

**Comment by Mozoloa** [comment]
Wait, you're right, you can change the routing with a snapshot I'm so dumb

**Comment by istnv** [comment]
This should be fixed in latest release
