### ISSUE TITLE
Feature Request: Behringer Xair12 with Bounty

### ISSUE THREAD

**Issue by JanosDakzinger** [bitfocus/companion-module-behringer-xair#5]
Hey  guys. 
I'm a sopundengineer from Berlin and i'm building a headless setup in the moment with the stream deck and a behringer Xair12 for interpreters to be able to interpret zoom conferences from home. 
I need to get visual feedback from the Xair to the streamdeck which Snapshot on the Behringer is activated (i.e. button one or two) 
I need this by thursday and i can offer 150,- € 
would be awesome if anyone is up for the task.
please don't hesitate to reach out.

Thanks alot in advance

janos@cog-records.com

**Comment by krocheck** [comment]
New build coming

**Comment by JanosDakzinger** [comment]
great :-)

**Comment by JanosDakzinger** [comment]
sweet its working.

@istnv send me your paypal buddy

**Comment by JanosDakzinger** [comment]
@istnv 
hey, i found one small bug. 
when i boot the system and companion comes on, i can't at first get the non selected snapshot to load or to get the feedback of it. i first have to push the selected one once and then it works like it should. 
in the link you find a short video of what i mean

https://drive.google.com/open?id=1TiT5HSfosrqTVT178djxuOg8E_IqRmal

thanks in advance

Janos

**Comment by krocheck** [comment]
@JanosDakzinger can you put the `s_index` variable in a separate button and report if it follows the same behavior as you press between those two snapshots?

**Comment by JanosDakzinger** [comment]
one sec

**Comment by JanosDakzinger** [comment]
yeah it's the same

https://drive.google.com/open?id=1pfv2qngklAKXKRt6PvpsR2INZE2wdlOt

**Comment by krocheck** [comment]
Its looks like you added the feedback to the button?  Are you familiar with dynamic variables?  You would actually in the button's text/label type `$(` and you'll get a dropdown of variables.  The default 'label' for the Xair instance is `xair`, so unless you changed that you'd type in $(xair:s_index)
![image](https://user-images.githubusercontent.com/749812/80628705-c6136300-8a1f-11ea-98cd-3c1d07150c46.png)
Initially the button text may show $NA, but after that it should start showing the index number as the snapshot changes.

**Comment by JanosDakzinger** [comment]
got you. one sec

**Comment by JanosDakzinger** [comment]
snapshot doesnt load

https://drive.google.com/open?id=1nGU4AwaLHi4yXWTuIExJmL548HjwrZYk

**Comment by istnv** [comment]
Just read through this. (Different time zone)  I'm looking into it.

**Comment by krocheck** [comment]
@istnv make you pull the latest code.  I already dropped one fix here.

**Comment by istnv** [comment]
@krocheck I'll need to re-fork and rearrange some files. 
JS is not my primary language and you are more familiar with the feedback/action options available.

**Comment by krocheck** [comment]
My assessment without having a unit to play with is this is an issue on the xair end.  I have no explanation as to why, but nothing I'm seeing would prevent the command from firing nor receiving the update.

**Comment by istnv** [comment]
I just loaded a fresh copy with your patches. Everything works as expected and I am not encountering that problem.

**Comment by krocheck** [comment]
@JanosDakzinger and @istnv what firmware versions are you running?

**Comment by istnv** [comment]
I'm going to download the windows build and run from a console to watch the logs.

**Comment by JanosDakzinger** [comment]
1.17

**Comment by istnv** [comment]
1.17

**Comment by istnv** [comment]
Companion restores the button states as much as possible (latch on does not get saved, darn).
This is a timing problem. I was able to reproduce once:
- Companion starts and displays the last button states, showing an old active snapshot (DE)
- The mixer is actually in a different snapshot (the other button) (EN)
- The module somehow 'misses' the initial snapshot query which would show the correct status
- The mixer is already in the other snapshot, so nothing 'changes' when you push the 'other' button
Lost UDP packets are hard to detect.

**Comment by istnv** [comment]
@JanosDakzinger There is a new build with a couple of fixes.

**Comment by JanosDakzinger** [comment]
sweet, let me check

**Comment by JanosDakzinger** [comment]
looks good

**Comment by istnv** [comment]
@JanosDakzinger my paypal is jjr@ayesti.com

**Comment by JanosDakzinger** [comment]
got it?

**Comment by istnv** [comment]
not yet

**Comment by istnv** [comment]
There now. Thanks!

**Comment by JanosDakzinger** [comment]
thank You buddy
