### ISSUE TITLE
[Feature Request] Store and Recall mute status of a channel

### ISSUE THREAD

**Issue by Ajonymous** [bitfocus/companion-module-behringer-xair#53]
The option to store and recall the mute status of a channel.

I have a 'PTT' button on companion which mutes specific channels on press and unmutes them on release. This works well but I would like the ability to return the channel to its original state on release. I.e. if the channel is already muted before I press the button, it is to stay muted on release. Toggle won't work in this instance as if the channel is originally muted, toggle with unmute it while the button is pressed.

Hope this makes sense. Happy to answer any questions.

**Comment by istnv** [comment]
There may be a way to do this with variables and triggers. I need more coffee first :)

**Comment by istnv** [comment]
There is a way to accomplish this. I'm using channel 12 as an example.
-- Create a variable for each channel involved (like `mc12` for channel 12 is muted)
Four triggers each channel:
-- Feedback `Channel muted ON` Action `Set mc12 = 1` 
-- Feedback `Channel OFF` Action `Set mc12 = 0`
-- Feedback `Check variable mc12 = 0` Action `Channel Mute 12 OFF`
-- Feedback `Check variable mc12 != 0` Action `Channel Mute 12 ON`
For your PTT button:
Down Action `Modify .. with math, mc12 'Plus' 1`
Up Action `Modify .. with math, mc12 ' Minus' 1`

Explanation:
Trigger will mute channel if the variable is not 0 and unmute when variable is 0.
Adding 1 to a muted channel, variable is set to 2, (not 0 = mute)
Minus 1 will return variable to 1, still muted.

**Comment by Ajonymous** [comment]
@istnv  Genius! Thanks for that. I will give it a try.
