### ISSUE TITLE
Variable list is not complete

### ISSUE THREAD

**Issue by jfou87** [bitfocus/companion-module-behringer-xair#56]
Hello, 
In the version [2.4.1 (2.4.1+4898-v2-4.1-9646192a), I used to display the value of the channel level in a button.
I own a XR16 with last firmware version.

There's a list of variable in Companion.
In my case in use the variable `$(xair:f_ch2_d)` or `$(xair:f_ch2_p)`
Those variable are present for all channels (as far I know, because I didn't use all channels, maybe the first 8)
But it miss for channel one. 
I can't find `$(xair:f_ch1_d)` or `$(xair:f_ch1_p)`

I think this is a simply forgetting. 
Can you add this ? 

Thank you so much !

**Comment by istnv** [comment]
This is fixed in update #54.
Waiting for core devs to update the release package.

**Comment by jfou87** [comment]
Thank you so much :-)
