### ISSUE TITLE
Fader adjust broken

### ISSUE THREAD

**Issue by Julusian** [bitfocus/companion-module-behringer-xair#59]
Hope I post the error correctly here (I'm new to Github but have been using Companion for a very long time). The "Fader adjust" no longer reacts to the Behringer xair module.
The "Fader set" or "Mute" e.g. work without problems.
In the log of the connection I can see the events for other buttons (e.g. mute). E.g.:
debug: received /ch/01/mix/on from
debug: received /ch/02/mix/on from
But when I assign buttons with "Fader adjust" and press them, I don't see any events in the debug log.
At the moment I'm on version 3.0.0+5713-beta-cdefdadf. Unfortunately, I can no longer say from which version the functions were no longer there. I think so far 2 weeks.

_Originally posted by @NefDak in https://github.com/bitfocus/companion/issues/2157#issuecomment-1464869764_

**Comment by istnv** [comment]
I just downloaded 3.0.0+5716 to test. Those actions work correctly.

**Comment by NefDak** [comment]
I reset the companion configuration, reconnected the X-Air and reassigned 2 buttons as a test. Same result: Fader Adjust doesn't work, Fader Set works. I noticed the same with the "Send level Set" AND "Send Level Adjust". Debug log does not record any data here either.

**Comment by istnv** [comment]
I was testing set vs adjust. There were a couple of property name changes that were not completed for the upgrade to V3. Also a couple of typos tossed in.
This should be fixed soon.

**Comment by istnv** [comment]
Fixed in latest release.

**Comment by WestonAtGrand** [comment]
would this be the appropriate place to mention the "xair: USB/Aux In Fader Adjust" is actually controlling "xair: Main LR Fader Adjust"?

**Comment by istnv** [comment]
Yes and no. Create a new issue.
