### ISSUE TITLE
Module crashes right after adding

### ISSUE THREAD

**Issue by GrueneNeun** [bitfocus/companion-module-behringer-xair#65]
I installed Companionpi with Companion 3.0.0+5758-beta-cead4511 via install.sh.

It starts as it should an for example the Blackmagic Design Atem Module works as expected.
But if I try to add the Behringer Xair Module, it says "Connection Config unavailabe" and in syslog:

`Mar 20 22:08:38 nettop launch.sh[6277]: 2023-03-20T21:08:38.389Z info #033[38;5;26;1mInstance/ModuleHost#033[0m Starting connection: "xair"(2DNS82BS8fL2QOQ6tZ4Ya)
Mar 20 22:08:39 nettop launch.sh[6277]: 2023-03-20T21:08:39.146Z warn #033[38;5;26;1mInstance/ModuleHost#033[0m Instance "xair" failed to init: Error: Cannot convert undefined or null to object TypeError: Cannot convert undefined or null to object
Mar 20 22:08:39 nettop launch.sh[6277]:     at Function.keys (<anonymous>)
Mar 20 22:08:39 nettop launch.sh[6277]:     at p.getConfigFields (/opt/companion/bundled-modules/behringer-xair/main.js:2:386800)
Mar 20 22:08:39 nettop launch.sh[6277]:     at /opt/companion/bundled-modules/behringer-xair/main.js:2:325839
Mar 20 22:08:39 nettop launch.sh[6277]:     at /opt/companion/bundled-modules/behringer-xair/main.js:2:251398
Mar 20 22:08:39 nettop launch.sh[6277]:     at t.default._tryToStartAnother (/opt/companion/bundled-modules/behringer-xair/main.js:2:250445)
Mar 20 22:08:39 nettop launch.sh[6277]:     at /opt/companion/bundled-modules/behringer-xair/main.js:2:251605
Mar 20 22:08:39 nettop launch.sh[6277]:     at new Promise (<anonymous>)
Mar 20 22:08:39 nettop launch.sh[6277]:     at t.default.add (/opt/companion/bundled-modules/behringer-xair/main.js:2:251248)
Mar 20 22:08:39 nettop launch.sh[6277]:     at p._handleInit (/opt/companion/bundled-modules/behringer-xair/main.js:2:325673)
Mar 20 22:08:39 nettop launch.sh[6277]:     at t.IpcWrapper.receivedMessage (/opt/companion/bundled-modules/behringer-xair/main.js:2:310703)
`

**Comment by istnv** [comment]
Try the latest release

**Comment by istnv** [comment]
This should be fixed with PR #68.
