### ISSUE TITLE
xair: Fader Adjust from internal variable

### ISSUE THREAD

**Issue by roopeberg** [bitfocus/companion-module-behringer-xair#67]
Hi,
For using Streamdeck+ rotarys I would like to be able to set levels with internal variable. 
Currently fadel Adjust is only able to be set by user for one numeric value and I would like to use companion custom internal variable value set by rotary. 

I am testing with 3.1.0 but this would be nice to have also on 2.4 side.

**Comment by istnv** [comment]
Many people are using the Streamdeck+ with these actions on 2.4 and 3.0.
Fader ADJUST uses an increment: Set Fader +/- X amount. Use -1 for left, +1 for right
Fader SET only allows one number: it will Set Fader directly to X

**Comment by istnv** [comment]
You can use the rotary knobs to adjust the faders already. 
Please explain the reasoning to add another layer of complexity/confusion (variables).

**Comment by roopeberg** [comment]
Ok now I see so fader adjust should work just like i would like it to but its not working at all..

I made just a simple regular button with one action to set level on channel 1 to -10 and this is what I get on the log:
23.03.21 11:43:55 Instance/Wrapper/xair: Error executing action: Assignment to constant variable.

Companion version is: 3.1.0 (3.1.0+5753-develop-540bfde8)<https://bitfocus.io/companion/>

[cid:988a34a0-8612-4792-ad6d-97763dbe2a31]


  *

Best regards,

Roope Berg
email ***@***.******@***.***>, mobile +358 (0)50 328 2371,
www.reloadmedia.fi<http://www.reloadmedia.fi/>
________________________________

**Comment by roopeberg** [comment]
It's related to companion version as now that I noticed 2.4 has also rotary actions I can use set levels ok.


Best regards,

Roope Berg
email ***@***.******@***.***>, mobile +358 (0)50 328 2371,
www.reloadmedia.fi<http://www.reloadmedia.fi/>
________________________________

**Comment by istnv** [comment]
I don't know how often the v3.1 betas are updated.
Most of the recent updates are applied to v3.0. 
That `assignment to constant` is fixed in v3.0

**Comment by roopeberg** [comment]
Thanks for helping 🙂
I now that I noticed 2.4 has rotarys working I can get adjustments working.
But in the future it would be nice to have internal variables a possibility on these. Next idea that came to mind is to have Course / Fine adjust variable to be able to change rotary change speed from 1 to example 5 / rotary step.



Best regards,

Roope Berg
email ***@***.******@***.***>, mobile +358 (0)50 328 2371,
www.reloadmedia.fi<http://www.reloadmedia.fi/>
________________________________

**Comment by istnv** [comment]
You can set the amount in adjustment in `Fader adjust` from -100% to +100%.

**Comment by roopeberg** [comment]
Yes but if I would like to have on one rotary for channel 1 and would like to alter how much one step adjust the fader on mixer.
Thinking it would some times nice to have it advance 4 / -4 but also have ability to go finer adjustments.
This could be done by custom variable that has starting value of 4 and you would have one extra button that would togle this value from 1 to 4.
Then you just would use this variable as your adjust value.


Best regards,

Roope Berg
email ***@***.******@***.***>, mobile +358 (0)50 328 2371,
www.reloadmedia.fi<http://www.reloadmedia.fi/>
________________________________

**Comment by istnv** [comment]
This should be in the beta release soon.
