### ISSUE TITLE
Channel 1 has no dynamic variables for fader level

### ISSUE THREAD

**Issue by BinaryBurgr** [bitfocus/companion-module-behringer-xair#69]
As titled, connected to an XR16 and none of the dynamic variables for channel 1's level are generating properly (`f_ch1_d`, `f_ch1_p`, `f_ch1_rp`). They don't appear in any list and can't be selected in, for example, the "internal: check variable value" feedback. Weirdly though, I can still reference them fine within a button title, if I type them manually. Disable/re-enabled the module, restarted Companion, nothing helps. Nothing of note in the logs either, just sync successful. Ch 1 & 2 are linked in my file, so I can just reference ch2's level for now, but it's weird that ch1 doesn't work.

companion: 			`2.4.2`
behringer-xair: 		`1.6.11`

X-Air firmware: 		`1.18`

**Comment by istnv** [comment]
This was fixed in update #54, v1.6.12 and is waiting for a new 2.4 build
Companion 3.0 has these updates, I don't know when a new 2.4 build will be released.
