### ISSUE TITLE
Crashed

### ISSUE THREAD

**Issue by srinivasvizag** [bitfocus/companion-module-behringer-xair#70]
system: ** Connection started **
Starting up module class: p
Sentry disabled
Module-host accepted registration
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: p
Sentry disabled
Module-host accepted registration
system: ** Connection stopped **
system: ** Connection started **
Starting up module class: p
Sentry disabled
Module-host accepted registration

**Comment by istnv** [comment]
This should be fixed, just waiting to be included in the core release.
