### ISSUE TITLE
BUG - Solo level adjust/set non functional 

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#78]
As the tittle says, so far I've only tested with FX returns into Bus and Sends. If I don't set a fade duration, the fader won't move

**Comment by istnv** [comment]
This works fine for me. Which module version? (Top of the help file)

**Comment by Mozoloa** [comment]
![image](https://github.com/bitfocus/companion-module-behringer-xair/assets/20817233/87f6a7bf-b93b-43e8-93e0-64538ad0b9ad)
 well this is awkward
I believe git pull tells me `already up to date` but maybe I'm doing something wrong lemme check

**Comment by Mozoloa** [comment]
Okay this seems to be solved after I nuked the git and recloned it, I was using some shady fork I believe but now I have another problem so let me hijack this issue:
![image](https://github.com/bitfocus/companion-module-behringer-xair/assets/20817233/8b2ff35e-53ed-42f4-ba89-c8768ed938f9)

The solo level can't be adjusted because there's no amount, and can't be set as there are two  **"Solo Level Adjust"**

**Comment by istnv** [comment]
That's odd :) I'll look into the solo stuff today.

If you are cloning the repo, the version is in package.json. The help file only shows the version after packaging.

**Comment by Mozoloa** [comment]
Then it's "version": "2.2.0"

**Comment by istnv** [comment]
Just found the solo problem. I'll update in a few minutes.

**Comment by istnv** [comment]
That fixes it for me :)

**Comment by Mozoloa** [comment]
While the actions reappeared, adjusting and setting doesn't seem to change the actual solo level on my end

**Comment by istnv** [comment]
Fat fingers caused an 'undo' before commit :/

**Comment by istnv** [comment]
try v2.2.2

**Comment by Mozoloa** [comment]
fixed ! (as far as I can see) thanks a lot
