### ISSUE TITLE
[BUG] Feedbacks for gate (at least) not working on companion 3.3.0

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#93]
Just realised my gates feedback didn't work on companion 3.3.0+6991-stable-b27baf94 that I believe came with an update of this module.
I just created a simple button that's supposed to change text color when channel 1 gate is on and nothing changes.

Other feedbacks seem fine afaik but I haven't tested much

**Comment by istnv** [comment]
Not sure what is happening here. I'll look over it today.

**Comment by istnv** [comment]
Should be in beta release today
