### ISSUE TITLE
I'm gonna need help!

### ISSUE THREAD

**Issue by GNU-Username** [bitfocus/companion-module-behringer-xair#95]
Please help,

I have a Midas XR18, trying to integrate your Companion module, but it's Crashed.

When I select it, it continually tries to connect and fails, but doesn't let me do anything except cancel the retry.
[module-log-6_1_2024-8_55_50 AM.csv](https://github.com/user-attachments/files/15523772/module-log-6_1_2024-8_55_50.AM.csv)

I've tried deleting the module and re-installing, restarting the computer, restarting the Midas, and disabling every other Companion Module.

Not sure what to try next.

(FYI: I also have the M-AIR Edit app working on two machines, as well as an X-Touch controller.  So the Midas can be reached from the computer.  And I've tried the module with Everything else disconnected.)

**Comment by GNU-Username** [comment]
Soooo....

Typing that made me think to try the Other computer and it worked!
It is running Companion 3.0 whilst the new one is running 3.3.0.

Is that the problem, that the module is not working with the latest "Stable" 
version of Companion?

**Comment by istnv** [comment]
That is a known issue fixed in the beta release. Should be available in a new stable update soon.

**Comment by GNU-Username** [comment]
Thanks!
And Great work.
