### ISSUE TITLE
[BUG] Laggy feedbacks on 3.3.0-3.3.1

### ISSUE THREAD

**Issue by Mozoloa** [bitfocus/companion-module-behringer-xair#96]
As you can see in this video, xair feedbacks are laggy, delayed by sometimes close to a second. In contrast, the upper left button has an internal feedback that's instant as you can see in the end.
https://github.com/bitfocus/companion-module-behringer-xair/assets/20817233/28cfeee8-3969-4a3d-8615-bfe39a0b2e2a

No log seem to show anything when I press the buttons so I don't know where to check for problems

**Comment by istnv** [comment]
I have noticed that on some channels and I'm not sure where the delay is. All feedbacks are live, the button changes when the mixer reports a change.
Main L/R mute or duck (button goes grey if lower than -40) are almost instant.
Other channels you can see a delay between press mute and button change.
I'm swamped this weekend, but I'll investigate more soon.

**Comment by istnv** [comment]
@Julusian  Any ideas?
There is nothing in the module that would account for the difference in response time.
The relevant code is the same for channels vs l/r main:
```
	switch (leaf) {
		case 'on':
		case 'lr':
			this.xStat[node].isOn = !!v
			this.checkFeedbacks(this.xStat[node].fbID)
			break
```
Mute feedback for LR is instant where Channel 14 is almost 1/2 second delayed.

**Comment by Mozoloa** [comment]
on stable 3.4.2 i have the glitch still on gate feedbacks, I have not tested other effects
