### ISSUE TITLE
$(xair:s_index) is empty after set Shnapshot

### ISSUE THREAD

**Issue by Suenee** [bitfocus/companion-module-behringer-xair#97]
1. Power On XR18 and wait 3 minutes atleast for full initiation of mixpult
2. use companion buttons to select different Snapshot
3. `$(xair:s_index)` and `$(xair:s_name)` is empty
4. snapshot is set anyway

OS: **Win10**
Companion: **3.3.1 (3.3.1+7001-stable-ee7c3daa)**
Hardware: **XR18**

Report updated: 2024-09-11

**Comment by istnv** [comment]
Fixed in beta release

**Comment by Suenee** [comment]
> Fixed in beta release

Bug is again here:

Companion 3.5.1
OS: Win10
Hardware: XR18

**Comment by istnv** [comment]
I have tried Windows and Ubuntu with Companion 3.5.1.
The variables are updated correctly.
